version: "3.9"
services:
  predictor:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: predictor
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - 8080:5000
    networks:
      - stockstalker-network
    command: >
      bash -c "coverage run -m unittest discover
      && coverage report -m --fail-under=90"

networks:
  stockstalker-network:
    driver: bridge
