version: "3.9"
services:
  predictor:
    restart: always
    image: predictor_test
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: predictor
    volumes:
      - ./predictor:/usr/src/app/predictor
      - ./saved_model:/usr/src/app/saved_model
      - ./tests:/usr/src/app/tests
      - ./utils:/usr/src/app/utils
      - ./app.py:/usr/src/app/app.py
    env_file:
      - .env
    ports:
      - 8080:5000
    networks:
      - stockstalker-network
    command: >
      bash -c "coverage run -m unittest discover
      && coverage report -m --fail-under=90"

networks:
  stockstalker-network:
    driver: bridge
