version: "3.9"
services:
  predictor:
    restart: always
    image: predictor
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: predictor
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - 8080:5000
    networks:
      - stockstalker-network

networks:
  stockstalker-network:
    driver: bridge
