version: "3.9"
services:
  predictor:
    restart: always
    container_name: predictor
    image: index.docker.io/starlightromero/stockstalker-predictor
    env_file:
      - .env
    networks:
      - stockstalker-network

networks:
  stockstalker-network:
    driver: bridge
