FROM python:3.9-buster

LABEL decription="Development image for StockStalker predictor."

WORKDIR /usr/src/app

HEALTHCHECK --interval=5m --timeout=30s --retries=2 \
    CMD curl -f http://localhost:8080/predictor/AAPL || exit 1

COPY  requirements.txt .
COPY  requirements_dev.txt .

RUN pip install --no-cache-dir -r requirements_dev.txt

COPY . .

ENV FLASK_APP=app.py
ENV FLASK_ENV=development

EXPOSE 5000

CMD ["flask", "run", "--host=0.0.0.0"]
